examples/music/src/chatifyActionsSchema.ts
examples/music/src/endpoints.ts
examples/music/src/input.txt
examples/music/src/main.ts

Added the functionality to play a playlist in the music example. This will populate the queue in the Spotify player so you can go forward/back songs.
Before, the first song in the playlist was being played. This does not populate the queue in the Spotify player, so you can not continue listening to the playlist or go to the next song.
Changes:
- Added `getPlaylist` to `chatifyActionsSchema.ts`
- Added `Playlist` type to `chatifyActionsSchema.ts`
- Updated `play` to take in `item: TrackList | Playlist`
- Added `contextUri` param to `play()` in `music/src/endpoints.ts`
Note:
The `Playlist` type is set to `unknown`. I first tried setting it to `{ name: string }` but, I was getting poor results with this. Using GPT 3.5, it was attempting to pass the name directly into the play function and …

Add play playlist functionality to music example

---

examples/music/src/chatifyActionsSchema.ts
examples/music/src/endpoints.ts
examples/music/src/input.txt
examples/music/src/main.ts
examples/music/src/playback.ts
package-lock.json

Added functionality for skipping to the next track, the previous track, and shuffling tracks to the music example. 
- Removed `pause` from the chatify actions API and replaced it with `controlPlayback`.
- Added `PlaybackAction` to the chatify actions as a parameter to `controlPlayback`.
- Added `playback.ts` to contain handlers for the playback state change functions.
- Updated local parser in `main.ts` to handle local parsing of next, previous, and shuffle.
Added new status display for toggling shuffle on and off:

Add next, previous, and shuffle functionality to music example

---

site/src/docs/introduction.md

Fixes several typos in the `Introduction` doc.

Fix typo in Introduction doc

---

.gitignore
src/model.ts

Some Open AI users can belong to multiple organizations within the same account.  This PR adds support for including **OpenAI-Organization** header. 
[https://platform.openai.com/docs/api-reference/requesting-organization](url)
The PR also includes a few additions to .gitignore

Support OpenAI Organization ID

---

src/model.ts

Changes Made:
Removed the colon after "@param org" in the JSDoc comments.
Reason for the Change:
The JSDoc comments were updated to adhere to the convention of not including a colon after the "@param" tag.

fix unnecessary colon in JSDoc

---

examples/music/src/chatifyActionsSchema.ts
examples/music/src/endpoints.ts
examples/music/src/input.txt
examples/music/src/main.ts

When using the music example, I found I wanted to see what tracks were up next in my queue. This PR adds functionality to show the current queue up to the next 20 tracks.
- Added `getQueue()` to the chatify actions API
- Added a `getQueue` function to `endpoints.ts`
- Added a handler in `main.ts` to get and print the queue using the existing `printTrackNames` function
- Added visualizations to make it easier to see were the queue begins and ends:

Add getQueue functionality to music example

---

examples/calendar/package.json
examples/coffeeShop/package.json
examples/math/package.json
examples/music/package.json
examples/restaurant/package.json
examples/sentiment/package.json
package-lock.json

This is an alternative to #89, and also fixes #81.
This worked for me but not for @DanielRosenwasser; I did see a bunch of time spent idealTree-ing but that happens when you change the tree, it seems.
There are other reasons to take #89 instead, mainly, perf.

Add typechat to example package deps

---

examples/calendar/package.json
examples/coffeeShop/package.json
examples/math/package.json
examples/music/package.json
examples/restaurant/package.json
examples/sentiment/package.json

The "main" entry point for the samples previously pointed to the non-existent 'index.js'.
Fixing this allows people to run samples with the shorthand `node .`, which consults ./package.json for the entry point.
Of course, `node ./dist/main.js` still works too.
I did not update the readme or examples.md to use `node .`, since I thought this was less obvious, but can if desired.

examples: fix "main" entry point in package.json

---

src/model.ts
src/typechat.ts

This PR adds support for prompt roles, i.e. prompt sections tagged with `"system"`, `"user"`, or `"assistant"` roles. TypeChat uses the `"user"` role for prompts it generates and the `"assistant"` role for previous LLM responses (which will be part of the prompt in repair attempts). TypeChat currently doesn't use the `"system"` role.
This PR also adds support for specifying a prompt preamble when processing requests. This makes it easier to implement chat-like interactions and conversation history.

Add support for prompt roles and prompt preambles

---

src/validate.ts

- fix typo.
- delete useless import.

Fix typo error

---

src/model.ts

When using [managed identity](https://learn.microsoft.com/en-us/azure/ai-services/openai/how-to/managed-identity) on Azure, the current code is not working and returning 401 errors.
The header `Authorization: `Bearer ${apiKey}` needs to be set for that use case.
I can also add a note in the documentation on how to use Azure managed identity if you want, let me know.

Fix authentication issue when using managed identity on Azure

---

python/.devcontainer/DockerFile
python/.devcontainer/devcontainer.json
python/examples/coffeeShop/demo.py
python/examples/coffeeShop/schema.py
python/pyproject.toml
python/src/typechat/__init__.py
python/src/typechat/_internal/model.py
python/src/typechat/_internal/ts_conversion/python_type_to_ts_nodes.py
python/tests/coffeeshop.py

- Add devcontainer for python and update hatch initialization. This ensures vscode will use the python interpreter in the hatch virtual environment.
- Add support to get comments from annotated fields. Update the coffeeShop examples to use annotation.
- Add helper method to create the typechat model for OpenAI and AzureOpenAI

Python: Add support for devcontainers and for comments in generated schema

---

python/.devcontainer/devcontainer.json
python/examples/calendar/demo.py
python/examples/calendar/schema.py
python/examples/restaurant/demo.py
python/examples/restaurant/schema.py
python/examples/sentiment/demo.py
python/examples/sentiment/schema.py
python/notebooks/calendar.ipynb
python/notebooks/coffeeShop.ipynb
python/notebooks/restaurant.ipynb
python/notebooks/sentiment.ipynb

This change adds examples that use straightforward schema translation: Sentiment, Restaurant and Calendar, Each example has a console demo as well as a jupyter notebook. The demos are ported from the typescript implementation of TypeChat.

Python: Add sentiment, calendar, and restaurant examples

---

python/examples/music/client.py
python/examples/music/demo.py
python/examples/music/schema.py
python/examples/music/spotipyWrapper.py
python/notebooks/music.ipynb
python/pyproject.toml

This change adds a music player example to the python typechat implementation. Unlike the typescript edition, this example does not rely on JsonProgram. Instead, the music player schema is exposed as a set of actions (and their corresponding parameter types). The model selects a sequence of actions to run. These are passed to a handler function that executes them in order.
The code is organized as follows:
- The *demo.py* file is the console app entry point - this is similar to previous python examples.
- The *schema.py* file defines the action types and their associated parameters.
- The *notebooks/music.pynb* file has an interactive Jupyter notebook for the music scenario.
- The *client.py* file has the logic for executing schmatized actions against the spotify API
- For this example, …

Python: Add music player example

---

python/examples/healthData/demo.py
python/examples/healthData/input.txt
python/examples/healthData/schema.py
python/examples/healthData/translator.py
python/notebooks/healthData.ipynb

This change adds an example of a TypeChat translator with history. Specifically, the translator keeps the previous agent responses and adds them the prompt, allowing the model to take them into account. In the health data example, the agent helps the user fill out information on their health history, current conditions and medication. The agent asks clarifying questions and keeps track of the data provided in the course of a conversation. This example is ported from the TypeChat.Net implementation.
Note: This sample works best with GPT 4

Python: Add Health Data example

---

python/.devcontainer/DockerFile
python/.devcontainer/devcontainer.json
python/examples/calendar/schema.py
python/examples/coffeeShop/schema.py
python/examples/healthData/schema.py
python/examples/healthData/translator.py
python/examples/math/program.py
python/examples/math/schema.py
python/examples/math/schemaV2.py
python/examples/music/client.py
python/examples/music/schema.py
python/examples/music/spotipyWrapper.py
python/examples/restaurant/schema.py
python/examples/sentiment/schema.py
python/pyproject.toml
python/pyrightconfig.json
python/src/typechat/_internal/model.py
python/src/typechat/_internal/result.py
python/src/typechat/_internal/translator.py
python/src/typechat/_internal/ts_conversion/python_type_to_ts_nodes.py
python/src/typechat/_internal/ts_conversion/ts_node_to_string.py
python/src/typechat/_internal/ts_conversion/ts_type_nodes.py
python/src/typechat/_internal/validator.py
python/tests/coffeeshop.py

This change updates the core implementation and the examples to run python 3.11
- Use typing_extensions package
- Adjust some syntax e.g. f-strings to align to 3.11
- Update project dependencies and the devcontainer definition

Python: update implementation to use python 3.11

---

examples/healthData/README.md
examples/healthData/package.json
examples/healthData/src/healthDataSchema.ts
examples/healthData/src/input.txt
examples/healthData/src/main.ts
examples/healthData/src/translator.ts
examples/healthData/src/tsconfig.json
package-lock.json
python/examples/healthData/translator.py

This is based on the healthData .Net examples. The code works best with gpt-4.

Adding healthData sample for TypeChat

---

python/examples/healthData/translator.py
python/examples/math/program.py
python/examples/multiSchema/router.py
python/src/typechat/_internal/translator.py
python/tests/hello_world.py

The `indent`/`dedent` logic was fragile to refactoring, so I've just moved the string contents over to the gutter.
Additionally, there were a few type-checking issues that were introduced in the samples that I've cleaned up.

Remove indent/dedent, fix up some type-checking errors.

---

python/src/typechat/_internal/ts_conversion/python_type_to_ts_nodes.py
python/tests/hello_dataclasses.py
python/tests/hello_world.py

This change enables translation of dataclasses into TypeScript schemas. Using dataclasses allows developers to operate over actual Python objects - in contrast, if we took an approach where we only permitted `TypedDict`s, developers would be restricted to only operating over dictionaries. With this, schemas can be generated from one, the other, or a mix of both.
Fixes #160

Add support for translating dataclasses

---

python/examples/math/demo.py
python/examples/math/program.py
python/examples/multiSchema/agents.py
python/examples/music/spotipyWrapper.py
python/notebooks/math.ipynb
python/pyproject.toml
python/src/typechat/__about__.py
python/src/typechat/__init__.py
python/src/typechat/_internal/interactive.py
python/src/typechat/_internal/model.py
python/src/typechat/_internal/ts_conversion/python_type_to_ts_nodes.py

This PR makes the following changes
* Further readies the repository for the upcoming release.
* Set version to 0.0.2 (0.0.1 is already out)
* Update the classifiers list
* Removes many `# type: ignore` comments and `@no_type_check` decorators (apart from the ones in `music`)
* Removes all unmasked type errors.
* Hides the `DefaultOpenAIModel` class in favor of just exposing `create_language_model`.
* Corrects the `process_requests` function to correctly handle `quit` and `exit` input (each line contains a trailing newline)
* Simplifies the evaluator in the `math` example.
I didn't spend much time on the music sample - there's a lot of type suppressions there and that probably needs its own PR.
I spent a decent amount of time replumbing the `math` example - and eventually realized there …

Python housekeeping

---

typescript/README.md

- Fix error in the path to the typescript edition of typechat
- Add step to npm install before npm build

Add missing step in readme

---

python/src/typechat/_internal/ts_conversion/python_type_to_ts_nodes.py

This should address the issues in https://github.com/microsoft/TypeChat/pull/186#discussion_r1501340232 so that our schema translation output is deterministic, which is especially important for snapshots and baselines (see #165).

Use `OrderedDict` in place of `dict` and `set` when order matters.

---

python/pyrightconfig.json

Unfortunately this is a flag that is supported but nobody is expected set it normally, and no program can control it externally. See more at https://github.com/microsoft/pyright/issues/7330.

Unpin Python version so that CI can check across versions.

---

python/pyproject.toml
python/src/typechat/_internal/model.py

This change aligns the behavior of TypeChat for Python with that of its TypeScript counterpart with respect to Azure OpenAI usage.
While TypeChat for TypeScript simply accepted the fully-formed endpoint URL for chat completions [as documented here](https://learn.microsoft.com/en-us/azure/ai-services/openai/reference#chat-completions), the `openai` package made it so that individual components of that URL had to be threaded through piecemeal (i.e. the deployment name, the model name, the version number, and the API key). What that meant was (at least as far as I could tell), the logic didn't work for Azure OpenAI.
This PR makes it so that TypeChat only cares about the API key and the fully formed URL being placed in your `.env` file:
```
AZURE_OPENAI_API_KEY={your-api-key} …
```

Replace usage of OpenAI SDK with direct API calls via httpx.

---

.github/workflows/ci.python.yml
python/package-lock.json
python/package.json
python/pyrightconfig.json
python/src/typechat/__init__.py

Updates CI to use `annotate` instead of `no-comments` (https://github.com/jakebailey/pyright-action/commit/93a05d0fa01403810a642a4d49bca4aac45a76b3)
Updates Pyright to the latest version and adds back the `pythonVersion` setting (see https://github.com/microsoft/TypeChat/pull/195 and https://github.com/microsoft/pyright/issues/7330).

Python CI fixups

---

TypeChat.code-workspace

This ensures that Pyright/Pylance settings can be picked up when developing within the workspace.

Add a VS Code workspace file.

---

python/examples/math/program.py
python/examples/music/client.py
python/examples/music/schema.py
python/examples/music/spotipyWrapper.py
python/src/typechat/_internal/translator.py

The current model for TypeChat in Python is to construct a TypeScript schema and use it regardless of if there are issues with the input. This is possible because the translation process was designed to produce an approximation of some TypeScript schema while producing a set of errors.
Surprisingly, our `math` demo takes advantage of this, providing a Python type which can't be translated into a TS schema. But this still works well enough for the demo!
So by default, failure to construct a schema will now *always* raise an error; however, `TypeChatProgramTranslator` now takes an experimental named `_raise_on_schema_errors` parameter which can be specified as `False` to opt out of this behavior.

Raise when TypeScript schema construction produces errors.

---

python/examples/healthData/translator.py
python/src/typechat/__init__.py
python/src/typechat/_internal/model.py
python/src/typechat/_internal/translator.py

Allow models to take lists of PromptSections, allow translators to take preambles.

---

typescript/examples/calendar/package.json
typescript/examples/calendar/src/main.ts
typescript/examples/coffeeShop-zod/package.json
typescript/examples/coffeeShop-zod/src/main.ts
typescript/examples/coffeeShop/package.json
typescript/examples/coffeeShop/src/main.ts
typescript/examples/healthData/package.json
typescript/examples/healthData/src/main.ts
typescript/examples/healthData/src/translator.ts
typescript/examples/math/package.json
typescript/examples/math/src/main.ts
typescript/examples/multiSchema/package.json
typescript/examples/multiSchema/src/main.ts
typescript/examples/music/package.json
typescript/examples/restaurant/package.json
typescript/examples/restaurant/src/main.ts
typescript/examples/sentiment-zod/package.json
typescript/examples/sentiment-zod/src/main.ts
typescript/examples/sentiment/package.json
typescript/examples/sentiment/src/main.ts
typescript/package-lock.json

This PR does two things.
First, it fixes the `typescript/healthData` example by bumping the version and fixing up the example. In principle, I expect the changes should be the same as #197, but without any formatting changes other than import ordering
Second, it changes all our examples to use combine `dotenv` with `find-config` [as suggested here](https://github.com/motdotla/dotenv/issues/238#issuecomment-348017037) so that `.env` files can be placed at the top level of the repo.

Fix `typescript/healthData` and search upward for `.env` files in TS examples.

---

python/pyproject.toml
python/src/typechat/_internal/validator.py
python/tests/test_validator.py

In #201 and #208, I switched us over from using Pydantic's `validate_json` to `validate_python`. However, there's a subtlety. [From the docs](https://docs.pydantic.dev/latest/api/pydantic_core/#pydantic_core.SchemaValidator.validate_json):
> It also handles constructing the correct Python type even in strict mode, where `validate_python(json.loads(json_data))` would fail validation.
That might sound surprising if you don't catch what happens at each step. The subtlety here is that by the time data is loaded up from `json.loads`, it comes in as a `dict`. Under `strict=True`, that `dict` is not compatible with any type other than certain kinds of `dict`s and `TypedDict`s. So 
Pydantic already has issues at https://github.com/pydantic/pydantic-core/issues/712 and …

Fix validation against dataclasses

---

python/README.md
python/examples/README.md
python/pyproject.toml
typescript/README.md

In #207, I made it so that hatch would create a `.venv` in the repository root. The reason was to make common scenarios work better for editors (most which currently don't understand hatch).
Still, lots of people don't use Hatch, and in #215, @pamelafox pointed out that it's nice to have control over this stuff. So this PR makes it possible to use use pip directly with our `pyproject.toml`. To do so, dev-time dependencies for TypeChat, along with dependencies for our examples, are moved into their own respective arrays in `optional-dependencies`.
Since pip allows you to install "extras" (see [here](https://packaging.python.org/en/latest/guides/installing-using-pip-and-virtual-environments/#install-extras), [here](https://packaging.python.org/en/latest/specifications/dependency-specifiers/# …

Make it easier to use purely `pip` and `venv` instead of requiring Hatch

---

python/examples/sentiment/demo.py
python/examples/sentiment/schema.py
python/src/typechat/_internal/model.py
python/src/typechat/_internal/validator.py

While the actual `HttpxLanguageModel` is still in an `_internal` module, I want people to be able to experiment and be able to set the relevant attributes.
Also switches our sentiment example to be a dataclass.

Various doc updates and expose some internals

---

python/src/typechat/_internal/interactive.py

Importing the readline module and using input() instead of sys.stdin turns on command line editing, including history.
For a REPL dinosaur like myself this is essential. :-)

Use readline for interactive input

---

python/examples/healthData/translator.py
python/src/typechat/_internal/translator.py
python/tests/__snapshots__/test_translator.ambr
python/tests/test_translator.py

This PR adds a test for Python translators by mocking a model and snapshotting the log.
Based on feedback from @gvanrossum where he pointed out that we don't actually use the repaired prompt (I broke this in #203). Some of the fixes are already in https://github.com/microsoft/TypeChat/pull/238.

Actually test the Python translator

---

python/src/typechat/_internal/translator.py
python/tests/__snapshots__/test_translator.ambr
python/tests/test_translator.py

More Python translator fixes

---

python/src/typechat/_internal/interactive.py

This fixes #235 for Windows, where `import readline` doesn't work (nor is it needed).

Don't crash if we cannot import readline (e.g. on Windows)

---

typescript/src/model.ts

GPT-4-vision, GPT-4-omni and GPT-4-turbo allow multi-modal input, where images and text can be passed in the prompt. To support this, the content section of the prompt has an array of objects instead of just a string.

Enable passing images along with text for models that support multimodal input
